// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    try {
      if (isNewSupabaseApiKey(supabaseKey)) {
        const headers = new Headers(init?.headers);
        if (headers.get('Authorization') === `Bearer ${supabaseKey}`) {
          headers.delete('Authorization');
        }
        headers.set('apikey', supabaseKey);
        return await fetch(input, { ...init, headers });
      }
      return await fetch(input, init);
    } catch (err) {
      console.error('[Supabase fetch] error:', err);
      throw err;
    }
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = (process.env.SUPABASE_URL ?? '').trim();
    const SUPABASE_PUBLISHABLE_KEY = (process.env.SUPABASE_PUBLISHABLE_KEY ?? '').trim();

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    // Testa conectividade com o Supabase antes de prosseguir
    try {
      const ctrl = new AbortController();
      const timeoutId = setTimeout(() => ctrl.abort(), 8_000);
      const testRes = await fetch(`${SUPABASE_URL}/rest/v1/`, {
        method: 'GET',
        headers: { apikey: SUPABASE_PUBLISHABLE_KEY },
        signal: ctrl.signal,
      });
      clearTimeout(timeoutId);
      if (!testRes.ok && testRes.status !== 404) {
        console.warn(`[Supabase] health check respondeu ${testRes.status}`);
      }
    } catch (connErr) {
      const detail = connErr instanceof Error ? `${connErr.name}: ${connErr.message}` : String(connErr);
      console.error(`[Supabase] Não foi possível conectar em ${SUPABASE_URL}: ${detail}`);
      throw new Error(`Supabase inacessível do servidor: ${detail}. Verifique se a URL e a chave estão corretas no Vercel e se a rede permite a conexão.`);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Decodifica o JWT localmente para extrair o sub (userId)
    // sem depender de chamada de rede ao servidor Auth (getClaims/getUser)
    let claims: Record<string, unknown> | null = null;
    try {
      const payload = token.split('.')[1];
      if (payload) {
        const decoded = JSON.parse(atob(payload.replace(/-/g, '+').replace(/_/g, '/')));
        if (decoded && typeof decoded === 'object') claims = decoded;
      }
    } catch {
      // fallback: tenta getClaims como alternativa
    }

    if (!claims || !claims.sub) {
      const fallback = await supabase.auth.getClaims(token).catch(() => ({ data: null, error: new Error('getClaims failed') }));
      if (fallback.error || !fallback.data?.claims) {
        throw new Error('Unauthorized: Invalid token');
      }
      claims = fallback.data.claims as Record<string, unknown>;
    }

    return next({
      context: {
        supabase,
        userId: claims.sub as string,
        claims,
      },
    });
  },
);
